#include "keymap_common.h"
#include "led_l3.h"

const uint8_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /* Layer 0: QWERTY */
    KEYMAP(\
        ESC, F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9,  F10, F11, F12, NO,  FN1, HOME,PSCR,SLCK,PAUS, \
        GRV, 1,   2,   3,   4,   5,   6,   7,   8,   9,   0,   MINS,EQL, NO,  BSPC,NLCK,PSLS,PAST,PMNS, \
        TAB, Q,   W,   E,   R,   T,   Y,   U,   I,   O,   P,   LBRC,RBRC,BSLS,     P7,  P8,  P9,  NO,   \
        FN0, A,   S,   D,   F,   G,   H,   J,   K,   L,   SCLN,QUOT,NO,  ENT,      P4,  P5,  P6,  PPLS, \
        LSFT,NO,  Z,   X,   C,   V,   B,   N,   M,   COMM,DOT, SLSH,RSFT,     UP,  P1,  P2,  P3,  PENT, \
        LCTL,LGUI,LALT,NO,  NO,       SPC,      NO,       NO,  RALT,RCTL,LEFT,DOWN,RGHT,P0,  COMM,NO),  \
    /* Layer 1: Space fn */
    KEYMAP(\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  TRNS,TRNS,TRNS,TRNS,TRNS, \
        FN2, TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,     TRNS,TRNS,TRNS,NO,   \
        FN3, TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  TRNS,     TRNS,TRNS,TRNS,TRNS, \
        TRNS,NO,  TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,     TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,NO,  NO,       FN4,      NO,       NO,  TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO),  \
    /* Layer 2: Mouse */
    KEYMAP(\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,WH_U,     TRNS,TRNS,TRNS,NO,   \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  WH_D,     TRNS,TRNS,TRNS,TRNS, \
        TRNS,NO,  TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,BTN3,     MS_U,BTN1,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,NO,  NO,       TRNS,     NO,       NO,  TRNS,TRNS,MS_L,MS_D,MS_R,TRNS,TRNS,NO),  \
    /* Layer 3: Toggle */
    KEYMAP(\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  TRNS,TRNS,TRNS,TRNS,TRNS, \
        FN5, FN6, FN7, FN8, FN9, FN10,FN11,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,     TRNS,TRNS,TRNS,NO,   \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  TRNS,     TRNS,TRNS,TRNS,TRNS, \
        TRNS,NO,  TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,     TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,NO,  NO,       TRNS,     NO,       NO,  TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO),  \
    /* Layer 4: Function layer */
    KEYMAP(\
        SLEP,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  PWR, TRNS,TRNS,TRNS,TRNS, \
        TRNS,MSEL,VOLU,MPLY,PSCR,SLCK,PAUS,HOME,INS, DEL, END, TRNS,TRNS,TRNS,     TRNS,TRNS,TRNS,NO,   \
        CAPS,MPRV,VOLD,MNXT,TRNS,TRNS,LEFT,DOWN,UP,  RGHT,TRNS,TRNS,NO,  WSCH,     TRNS,TRNS,TRNS,TRNS, \
        TRNS,NO,  MUTE,TRNS,TRNS,TRNS, GRV,FN12,PGDN,PGUP,TRNS,TRNS,TRNS,     TRNS,TRNS,TRNS,TRNS,TRNS, \
        TRNS,TRNS,TRNS,NO,  NO,       TRNS,     NO,       NO,  TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO)
};

void action_function(keyrecord_t *record, uint8_t id, uint8_t opt)
{
    switch (id) {
      case 1:
        led_change_mode();
      break;
      case 2:
        rgb_change_mode();
      break;
      default:
      break;
    }
}

const uint16_t PROGMEM fn_actions[] = {
    [0]  = ACTION_LAYER_TAP_KEY(3, KC_CAPS),
    [1]  = ACTION_LAYER_MOMENTARY(4),
    [2]  = ACTION_MODS_KEY(MOD_RSFT, KC_GRV),
    [3]  = ACTION_LAYER_TAP_KEY(3, KC_ESC),
    [4]  = ACTION_LAYER_TAP_KEY(4, KC_SPACE),
    [5]  = ACTION_LAYER_SET_CLEAR(0),
    [6]  = ACTION_LAYER_TOGGLE(1),
    [7]  = ACTION_LAYER_TOGGLE(2),
    [8]  = ACTION_BACKLIGHT_LEVEL(BACKLIGHT_SWITCH),
    [9]  = ACTION_BACKLIGHT_LEVEL(BACKLIGHT_PCB),
    [10] = ACTION_FUNCTION(1),
    [11] = ACTION_FUNCTION(2),
    [12] = ACTION_MODS_KEY(MOD_LSFT, KC_INS)
};
